"""Feature indexing, mirrored from NeraChessNNUE/src/FeatureSet.cpp.

Training samples are stored as FENs, so the trainer needs its own indexer. It
must produce byte-identical indices to the engine's, otherwise the network
learns one input layout and is evaluated with another -- a failure mode that
shows up as a network that trains well and plays terribly.

Features are canonicalized horizontally on the perspective's own king: a
perspective whose king stands on files a-d reads every square reflected, so
that its own king always appears on files e-h. The two perspectives decide
independently. See ``arch.FEATURE_SET_VERSION``.

``tests/test_features.py`` checks this module against
``tests/feature_vectors.json``, which is generated by::

    ./bin/Release/NeraChessTests/NeraChessTests --nnue-feature-vectors

Regenerate that file whenever the feature set changes.
"""

from __future__ import annotations

from dataclasses import dataclass
from enum import IntEnum
from typing import Iterator

from . import architecture as arch


class Piece(IntEnum):
    """Piece encoding, matching NeraChessEngine::PieceType."""

    WHITE_PAWN = 0
    WHITE_KNIGHT = 1
    WHITE_BISHOP = 2
    WHITE_ROOK = 3
    WHITE_QUEEN = 4
    WHITE_KING = 5
    BLACK_PAWN = 6
    BLACK_KNIGHT = 7
    BLACK_BISHOP = 8
    BLACK_ROOK = 9
    BLACK_QUEEN = 10
    BLACK_KING = 11


class Perspective(IntEnum):
    WHITE = 0
    BLACK = 1


#: FEN piece letter to piece index.
FEN_PIECES = {
    "P": Piece.WHITE_PAWN,
    "N": Piece.WHITE_KNIGHT,
    "B": Piece.WHITE_BISHOP,
    "R": Piece.WHITE_ROOK,
    "Q": Piece.WHITE_QUEEN,
    "K": Piece.WHITE_KING,
    "p": Piece.BLACK_PAWN,
    "n": Piece.BLACK_KNIGHT,
    "b": Piece.BLACK_BISHOP,
    "r": Piece.BLACK_ROOK,
    "q": Piece.BLACK_QUEEN,
    "k": Piece.BLACK_KING,
}


def is_white(piece: int) -> bool:
    return piece < Piece.BLACK_PAWN


def relative_square(perspective: Perspective, square: int) -> int:
    """Square as seen from a perspective; Black sees the board flipped."""
    return square if perspective == Perspective.WHITE else square ^ 56


def relative_colour(perspective: Perspective, piece: int) -> int:
    """0 for the perspective's own pieces, 1 for the opponent's."""
    own = is_white(piece) == (perspective == Perspective.WHITE)
    return 0 if own else 1


def mirrored_square(square: int) -> int:
    """Horizontal reflection of a square: a<->h, b<->g, c<->f, d<->e.

    a1 is 0 and h1 is 7, so the low three bits hold the file and flipping them
    reflects the board about the d/e boundary.
    """
    return square ^ 7


class Orientation(IntEnum):
    """Which way round a perspective reads the board horizontally."""

    DIRECT = 0  # the own king already stands on files e-h
    MIRRORED = 1  # the own king stands on files a-d; squares reflect


def orientation_of_king(relative_king_square: int) -> Orientation:
    """Orientation a king square implies.

    Takes the perspective-relative square, which is what features are expressed
    in. The vertical flip preserves the file, so reading the file off the
    absolute square would give the same answer.
    """
    # Files a, b, c, d (0..3) mirror; e, f, g, h (4..7) stay put.
    if (relative_king_square & 7) < 4:
        return Orientation.MIRRORED
    return Orientation.DIRECT


def king_bucket(perspective: Perspective, king_square: int) -> int:
    """Feature-transformer matrix selected by the perspective's own king.

    Always 0 while ``INPUT_BUCKET_COUNT`` is 1. Kept as a function so that
    adding king buckets changes this module in one place, exactly as it does
    on the C++ side.
    """
    del perspective, king_square
    assert arch.INPUT_BUCKET_COUNT == 1, "king buckets need a real mapping here"
    return 0


@dataclass(frozen=True)
class View:
    """How one perspective's features are numbered.

    Mirrors ``NeraChessNNUE::FeatureSet::View``: which weight matrix the
    features index, and which way round the board is read. Both follow the
    perspective's own king, so the two perspectives of a position can and
    regularly do disagree.
    """

    perspective: Perspective
    orientation: Orientation = Orientation.DIRECT
    input_bucket: int = 0


def view_of_king(perspective: Perspective, king_square: int) -> View:
    """View for a perspective whose own king stands on the given square."""
    relative = relative_square(perspective, king_square)
    return View(
        perspective,
        orientation_of_king(relative),
        king_bucket(perspective, king_square),
    )


def oriented_square(view: View, square: int) -> int:
    """Square as a view numbers it: the vertical flip, then the reflection.

    The two operate on disjoint bits, so their order is a matter of exposition
    only.
    """
    relative = relative_square(view.perspective, square)
    if view.orientation == Orientation.MIRRORED:
        return mirrored_square(relative)
    return relative


def feature_index(view: View, piece: int, square: int) -> int:
    """Index of one (piece, square) feature within a perspective's input space.

    Layout::

        ((relative_colour * PIECE_TYPE_COUNT + piece_type) * SQUARE_COUNT
         + oriented_square) + input_bucket * PERSPECTIVE_INPUT_SIZE
    """
    colour = relative_colour(view.perspective, piece)
    piece_type = int(piece) % arch.PIECE_TYPE_COUNT
    square_index = oriented_square(view, square)

    index = (
        colour * arch.PIECE_TYPE_COUNT + piece_type
    ) * arch.SQUARE_COUNT + square_index
    return view.input_bucket * arch.PERSPECTIVE_INPUT_SIZE + index


def parse_fen_pieces(fen: str) -> list[tuple[int, int]]:
    """Piece placement of a FEN as ``(piece, square)`` pairs.

    Squares are 0..63 with a1 = 0 and h8 = 63, matching the engine's bitboard
    layout. Only the placement field is read; the rest of the FEN is ignored.
    """
    placement = fen.split()[0]
    pieces: list[tuple[int, int]] = []

    rank = 7
    file = 0
    for character in placement:
        if character == "/":
            rank -= 1
            file = 0
        elif character.isdigit():
            file += int(character)
        else:
            piece = FEN_PIECES.get(character)
            if piece is None:
                raise ValueError(f"unknown piece {character!r} in FEN {fen!r}")
            if not (0 <= rank < 8 and 0 <= file < 8):
                raise ValueError(f"piece outside the board in FEN {fen!r}")
            pieces.append((int(piece), rank * 8 + file))
            file += 1

    return pieces


def side_to_move(fen: str) -> Perspective:
    fields = fen.split()
    if len(fields) < 2:
        raise ValueError(f"FEN has no side-to-move field: {fen!r}")
    return Perspective.WHITE if fields[1] == "w" else Perspective.BLACK


def king_square(pieces: list[tuple[int, int]], perspective: Perspective) -> int | None:
    wanted = Piece.WHITE_KING if perspective == Perspective.WHITE else Piece.BLACK_KING
    for piece, square in pieces:
        if piece == wanted:
            return square
    return None


def view_of(pieces: list[tuple[int, int]], perspective: Perspective) -> View:
    """View a perspective's features must be numbered with.

    A position holding no king for that side -- only malformed test positions
    do -- reads ``DIRECT``, and ``FeatureSet::ViewOf`` makes the same choice.
    """
    king = king_square(pieces, perspective)
    if king is None:
        return View(perspective, Orientation.DIRECT, 0)
    return view_of_king(perspective, king)


def active_features(fen: str, perspective: Perspective) -> list[int]:
    """Every feature active for one perspective, sorted.

    Sorted so the result compares equal to the engine's sorted dump; the
    accumulator itself is order independent because it only sums columns.
    """
    pieces = parse_fen_pieces(fen)
    view = view_of(pieces, perspective)
    return sorted(feature_index(view, piece, square) for piece, square in pieces)


def both_perspectives(fen: str) -> tuple[list[int], list[int]]:
    """Active features for ``(side to move, other side)``.

    This is the order the output layer expects: the network always reads the
    moving side first.
    """
    stm = side_to_move(fen)
    other = Perspective.BLACK if stm == Perspective.WHITE else Perspective.WHITE
    return active_features(fen, stm), active_features(fen, other)


def iter_feature_names() -> Iterator[str]:
    """Readable name of every input feature, for debugging weight dumps.

    Square names are the canonical ones the index encodes -- already flipped
    for the perspective and mirrored onto the king side -- not the squares of
    any particular position.
    """
    files = "abcdefgh"
    types = ["pawn", "knight", "bishop", "rook", "queen", "king"]
    for bucket in range(arch.INPUT_BUCKET_COUNT):
        for colour in ("own", "their"):
            for piece_type in types:
                for square in range(arch.SQUARE_COUNT):
                    name = f"{files[square % 8]}{square // 8 + 1}"
                    yield f"bucket{bucket}/{colour}/{piece_type}/{name}"
